export const tagsList = [
    { label: 'Básico', value: 'basico' },
    { label: 'Avanzado', value: 'avanzado' },
    { label: 'Intermedio', value: 'intermedio' },
    { label: 'JavaScript', value: 'javascript' },
    { label: 'Python', value: 'python' },
    { label: 'C#', value: 'c#' },
    { label: 'ReactJs', value: 'reactjs' },
    { label: 'VueJs', value: 'vuejs' },
    { label: 'NextJs', value: 'nextjs' },
    { label: 'Gratis', value: 'gratis' },
    { label: 'Programación', value: 'programacion' },
    { label: 'Ciencia de Datos', value: 'ciencia-de-datos' },
    { label: 'IA', value: 'ia' },
    { label: 'Blockchain', value: 'blockchain' },
    { label: 'Cloud Computing', value: 'cloud-computing' },
    { label: 'Desarrollo Web', value: 'desarrollo-web' },
    { label: 'DevOps', value: 'devops' },
    { label: 'Ingles', value: 'ingles' },
    { label: 'Marketing Digital', value: 'marketing-digital' },
    { label: 'E-commerce', value: 'e-commerce' },
    { label: 'Negocios', value: 'negocios' },
    { label: 'Finanzas e Inversiones', value: 'finanzas-e-inversiones' },
    { label: 'Startups', value: 'startups' },
    { label: 'Diseño', value: 'diseño' },
    { label: 'Producto', value: 'producto' },
    { label: 'Becas', value: 'becas' }
];
